version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/db-data:/var/lib/mysql
  python:
    build: ./db-accessor
    container_name: db-accessor
    ports:
      - 8001:5672
    depends_on:
      - rabbitmq
  rabbitmq:
    build: ./mq
    container_name: mq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/etc/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log

