version: '3'

services:
  django-gunicorn:
    build: ./django-gunicorn
    container_name: django-gunicorn
    ports:
      - 8000:8000
    volumes:
      - ./django-gunicorn/static:/static
    env_file:
      - ./django-gunicorn/.env
        #command: /bin/bash -c "while true; do sleep 1; done"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./django-gunicorn/static:/static
    depends_on:
      - django-gunicorn


