version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./volumes/db-data:/var/lib/mysql
  
  db-accessor:
    build: ./db-accessor
    container_name: db-accessor
    ports:
      - 8001:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build: ./mq
    container_name: mq
    hostname: my-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./volumes/rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 15s
      retries: 5

