version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./volumes/db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mq
    hostname: my-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./volumes/rabbit-data:/var/lib/rabbitmq

